env: "local"

token_ttl: 1h
client_domen: "http://localhost:5173"

psql:
  username: "postgres"
  host: "user-postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

http_server:
  server_port: ":8080"
  timeout: 4s
  idle_timeout: 60s
  access_tokenTTL: 15m
  refresh_tokenTTL: 43200m

